; PlatformIO Project Configuration File
;
;   Freenove FNK0104B
;   ESP32-S3 + 2.8" ILI9341 + FT6336U capacitive touch
;

[env:freenove-fnk0104b]
extends = CYDS3_Base
board = freenove-fnk0104b
build_flags =
	${CYDS3_Base.build_flags}
	-DOTA_TAG='"FNK0104B"'
build_unflags =
	-DDISABLE_OTA
